# Generated by Django 3.2.4 on 2021-06-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField()),
                ('licence_plate', models.CharField(max_length=150, verbose_name='plaka numarası')),
                ('chasis_no', models.CharField(max_length=150, verbose_name='şase numarası')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.vehiclemodel')),
            ],
        ),
    ]
