# Generated by Django 3.2.4 on 2021-06-23 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210624_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.vehiclemodel'),
        ),
    ]
